### ISSUE TITLE
Thanks (again) for another great tool! 

### ISSUE THREAD

**Issue by AXGKl** [pawamoy/copier-pdm#1]
The template arrangement is super well executed - so transition from a productive project based on copier.poetry was really really smooth [1].

And: Yes, pdm rocks...
This *has* to be the future of python packaging - so glad you invested the work in supporting it, so well aligned with copier.poetry.

Cheers & Thanks again!!,
G.

PS: Again, a little problem to justify the issue here: 
Took me quite a while (had not all brains available) to find out that optional dev.dependencies are not yet supported in current pipx installed pdm version. Imho that would be worth a note or a comment in the generated pyproject.toml file, to not frustrate others when first trying `copier.pdm`. Not sure when this is supported.

**Comment by pawamoy** [comment]
Thank you for the kind words and report :smile: 
As frostming answered you on the other issue, you have to install the latest beta of PDM indeed, I'll add a note to the docs/README!
