### ISSUE TITLE
Copier doesn't use correct template from fork

### ISSUE THREAD

**Issue by hoangthienan95** [pawamoy/copier-pdm#20]
Thanks for the cool template! I have forked my own (https://github.com/hoangthienan95/copier-pdm/) and added my own [variable](https://github.com/hoangthienan95/copier-pdm/blob/a5e9a5e0b5a31c7112c2711f89c632bae2f1c002/copier.yml#L126) to be templated in [pyproject.toml](https://github.com/hoangthienan95/copier-pdm/blob/a5e9a5e0b5a31c7112c2711f89c632bae2f1c002/project/pyproject.toml.jinja#L78).

However, when I run `copier gh:hoangthienan95/copier-pdm test`, I don't see my `python_requirement` variable being asked and also the pyproject.toml `requires-python` field is still `">=3.7"`. Any idea how to fix this? New to copier and pdm :)

**Comment by pawamoy** [comment]
Copier will by default use the latest *tag*. If you didn't tag your commit, you can instruct Copier to use HEAD instead of the latest tag with `copier -r HEAD gh:hoangthienan95/copier-pdm test`.

**Comment by pawamoy** [comment]
Closing, feel free to ask anything again :slightly_smiling_face:
