### ISSUE TITLE
"pdm run doc" fails

### ISSUE THREAD

**Issue by srfoster65** [pawamoy/copier-pdm#27]
Thanks for sharing a great resource!

I have found an issue when using the command "pdm run doc"

```
> pdm run doc
INFO    -  Building documentation...
INFO    -  Cleaning site directory
../README.md ['C:\\Users\\Steve\\SynologyDrive\\development\\python\\test_app1\\docs']
ERROR   -  Error reading page 'index.md': Snippet at path '../README.md' could not be found
```

I believe this is caused by the nesting of the documentation folder "docs" inside a folder of the same name, and then attempting to reference README.md outside the root folder, docs.

The solution I have used is to update mkdocs.yml as follows

```yaml
markdown_extensions:
  ...
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: false
```

I could create my 1st pull request if you would prefer that route.
Steve

**Comment by pawamoy** [comment]
(I've edited your comment: multiline code blocks are written using triple backticks, check it out :slightly_smiling_face:)

**Comment by srfoster65** [comment]
I must apologise - I have been experimenting with 2 versions of copier-pdm - the comment above applies to https://github.com/pdm-project/copier-pdm - so sorry.

And thanks for correcting the formatting.

**Comment by pawamoy** [comment]
Oh I see, OK, no worries!
