### ISSUE TITLE
Option to use venvs using environment variable

### ISSUE THREAD

**Issue by DomWeldon** [pawamoy/copier-pdm#28]
Love the plugin, just had an issue where my virtual environments were named after their python versions (e.g., `3.8.17`, `3.9.17`) and I found that I kept getting muddled between venvs and PEP 582 style environments because I'd forget to add the `-e` flag to my commands.

Suggesting a new feature where there is an environment variable, `PDM_MULTIRUN_USE_VENVS` which when set to `1` will use virtual environments by default.

**Comment by pawamoy** [comment]
Sure, nice idea!

**Comment by DomWeldon** [comment]
Apologies - I put the issue in the wrong project initially. See this is now merged. Thanks.

**Comment by pawamoy** [comment]
Thanks!
