### ISSUE TITLE
double-quotes "pawamoy" not compatibile with win32

### ISSUE THREAD

**Issue by ximchi** [pawamoy/copier-pdm#32]
**Issue on Windows**
```bash
copier copy --trust "gh:pawamoy/copier-pdm" /path/to/your/new/project
``` 
results in ``invalid path 'project/docs/{% if author_username == "pawamoy" %}.overrides{% endif %}/main.html.jinja'`` .

&emsp;
**Solved by**
Changing ``"pawamoy"`` to ``'pawamoy'`` in  [`{% if author_username == "pawamoy" %}.overrides{% endif %}`](https://github.com/pawamoy/copier-pdm/tree/main/project/docs/%7B%25%20if%20author_username%20%3D%3D%20%22pawamoy%22%20%25%7D.overrides%7B%25%20endif%20%25%7D)

&emsp;
as documented here: "*On Windows, double-quotes are not valid characters in file and directory paths.*" [Copier-docs](https://copier.readthedocs.io/en/stable/configuring/#conditional-files-and-directories)

Thanks a lot for the great template 🙂

**Comment by pawamoy** [comment]
Damn Windows! Yep, I'll fix it, thanks for the report :slightly_smiling_face:

**Comment by pawamoy** [comment]
v0.16.10 :slightly_smiling_face:
