### ISSUE TITLE
What's the correct way to install test dependencies locally?

### ISSUE THREAD

**Issue by gadams999** [pawamoy/copier-pdm#33]
If I add a module such as `requests` to a project via `pdm add`, what is the proper way to ensure it gets added to all the versions of python when running `make tests`? I see in the GH workflow how it's being done, but not when developing locally.

Is this something pdm should do, pytest, or some other process?

**Comment by pawamoy** [comment]
That's a good question, it should be clarified in the docs. After having added a dependency with `pdm add`, you should simply run `make setup` again to synchronize dependencies for all the selected Python versions.

**Comment by pawamoy** [comment]
At some point I consider adding wrappers to PDM commands like `make add`, `make remove`, etc. I can reconsider :slightly_smiling_face:
